#Window
ROAD_WIDTH = 30
SCREEN_HEIGHT = 750
SCREEN_WIDTH  = 1000

#Vehicle
DELTA             = 4
STOPPING_DISTANCE = 5
MAX_SPEED         = 5
REACTION_TIME     = 8
ACCELERATION      = 0.1
BRAKING           = 0.1

#Bus
BUS_LENGTH         = 80
BUS_CAPACITY_RANGE = (75,100)

#Car
CAR_LENGTH         = 40
CAR_CAPACITY_RANGE = (1,4)

#Traffic Control
RED_TIME     = 300
YELLOW_TIME  = 100
BUS_PRIORITY = 200

#World
BUS_PROB = 0.1
MAX_TICK = -1